name = "mirrow-app"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-09-08"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = ["src", "public"]

[assets]
directory = "./dist"
binding = "ASSETS"